/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ha1.app;

import ha1.list.LinkedList;

import static ha1.utilities.StringUtils.join;
import static ha1.utilities.StringUtils.split;
import static ha1.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
